version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: usmail-db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: first
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  adminer:
    image: adminer:latest
    container_name: my-adminer
    ports:
      - "8080:8080"

volumes:
  postgres-data:

