// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'ar'
	| 'de'
	| 'en'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * h​e​l​l​o​ ​w​o​r​l​d
	 */
	message: string
	/**
	 * W​e​l​c​o​m​e​ ​T​o​ ​L​i​s​t​e​d​ ​a​p​p
	 */
	tagLine: string
	/**
	 * u​s​s​m​a​i​l
	 */
	developer: string
}

export type TranslationFunctions = {
	/**
	 * hello world
	 */
	message: () => LocalizedString
	/**
	 * Welcome To Listed app
	 */
	tagLine: () => LocalizedString
	/**
	 * ussmail
	 */
	developer: () => LocalizedString
}

export type Formatters = {}
